version: "3.1"
services:
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: blobscan
      MONGO_INITDB_ROOT_PASSWORD: blob4844
    volumes:
      - ~/.blobscan/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - blobscan
networks:
  blobscan:
    driver: bridge
